nondet_interface_1_bank_80_0(A,B,C,D,E,F,E,F) :- (A = 0).
nondet_interface_1_bank_80_0(A,B,C,D,E,F,G,H) :- (I = 0),summary_4_function_deposit__39_80_0(A,B,C,D,J,K,L,G,H),nondet_interface_1_bank_80_0(I,B,C,D,E,F,K,L).
nondet_interface_1_bank_80_0(A,B,C,D,E,F,G,H) :- (I = 0),summary_6_function_withdraw__79_80_0(A,B,C,D,J,K,L,M,G,H,N),nondet_interface_1_bank_80_0(I,B,C,D,E,F,K,L).
block_7_function_deposit__39_80_0(A,B,C,D,E,F,G,H,I,J,K) :- true.
block_8_deposit_38_80_0(A,B,C,D,E,F,G,H,I,J,K) :- (H = F),(A = 0),(I = G),block_7_function_deposit__39_80_0(A,B,C,D,E,F,G,H,I,J,K).
block_10_function_deposit__39_80_0(A,B,C,D,E,F,G,H,I,J,K) :- \+(L),(A = 1),\+(((L; (M = N)), (\+((M = N)); \+(L)))),(N =< 1158),(N >= 0),(N = (O + P)),(P =< 1158),(P >= 0),(P = msg_value(E)),(O =< 1158),(O >= 0),(O = J),(M =< 1158),(M >= 0),(M = K),(K = Q),(Q >= 0),(Q =< 1158),(Q =< 1158),(Q >= 0),(Q = select(mapping__address_to_uint256___tuple_accessor_array(I), R)),(R =< 146),(R >= 0),(R = msg_sender(E)),(S = I),(T = I),(I = mapping__address_to_uint256___tuple(store(mapping__address_to_uint256___tuple_accessor_array(U), V, W), mapping__address_to_uint256___tuple_accessor_length(U))),(X =< 1158),(X >= 0),(X = select(mapping__address_to_uint256___tuple_accessor_array(U), V)),(U = Y),(W =< 1158),(W >= 0),(W = (Z + A1)),(Z >= 0),(Z =< 1158),(Z =< 1158),(Z >= 0),(Z = select(mapping__address_to_uint256___tuple_accessor_array(Y), V)),(V =< 146),(V >= 0),(V = msg_sender(E)),(B1 = Y),(A1 =< 1158),(A1 >= 0),(A1 = msg_value(E)),(J = C1),(C1 >= 0),(C1 =< 1158),(C1 =< 1158),(C1 >= 0),(C1 = select(mapping__address_to_uint256___tuple_accessor_array(Y), D1)),(D1 =< 146),(D1 >= 0),(D1 = msg_sender(E)),(E1 = Y),(F1 = 0),(G1 = 0),block_8_deposit_38_80_0(H1,B,C,D,E,F,G,H,Y,G1,F1).
summary_3_function_deposit__39_80_0(A,B,C,D,E,F,G,H,I) :- block_10_function_deposit__39_80_0(A,B,C,D,E,F,G,H,I,J,K).
block_9_return_function_deposit__39_80_0(A,B,C,D,E,F,G,H,I,J,K) :- (A = L),\+(((M; (N = O)), (\+((N = O)); \+(M)))),(O =< 1158),(O >= 0),(O = (P + Q)),(Q =< 1158),(Q >= 0),(Q = msg_value(E)),(P =< 1158),(P >= 0),(P = J),(N =< 1158),(N >= 0),(N = K),(K = R),(R >= 0),(R =< 1158),(R =< 1158),(R >= 0),(R = select(mapping__address_to_uint256___tuple_accessor_array(I), S)),(S =< 146),(S >= 0),(S = msg_sender(E)),(T = I),(U = I),(I = mapping__address_to_uint256___tuple(store(mapping__address_to_uint256___tuple_accessor_array(V), W, X), mapping__address_to_uint256___tuple_accessor_length(V))),(Y =< 1158),(Y >= 0),(Y = select(mapping__address_to_uint256___tuple_accessor_array(V), W)),(V = Z),(X =< 1158),(X >= 0),(X = (A1 + B1)),(A1 >= 0),(A1 =< 1158),(A1 =< 1158),(A1 >= 0),(A1 = select(mapping__address_to_uint256___tuple_accessor_array(Z), W)),(W =< 146),(W >= 0),(W = msg_sender(E)),(C1 = Z),(B1 =< 1158),(B1 >= 0),(B1 = msg_value(E)),(J = D1),(D1 >= 0),(D1 =< 1158),(D1 =< 1158),(D1 >= 0),(D1 = select(mapping__address_to_uint256___tuple_accessor_array(Z), E1)),(E1 =< 146),(E1 >= 0),(E1 = msg_sender(E)),(F1 = Z),(G1 = 0),(H1 = 0),block_8_deposit_38_80_0(L,B,C,D,E,F,G,H,Z,H1,G1).
summary_3_function_deposit__39_80_0(A,B,C,D,E,F,G,H,I) :- block_9_return_function_deposit__39_80_0(A,B,C,D,E,F,G,H,I,J,K).
block_11_function_deposit__39_80_0(A,B,C,D,E,F,G,H,I,J,K) :- true.
summary_4_function_deposit__39_80_0(A,B,C,D,E,F,G,H,I) :- (J = state_type(store(balances(K), B, (select(balances(K), B) + L)))),((select(balances(K), B) + L) >= 0),((select(balances(K), B) + L) =< 1158),(L >= msg_value(E)),((block_prevrandao(E) + 0) >= 1),(block_basefee(E) >= 0),(block_basefee(E) =< 1158),(block_chainid(E) >= 0),(block_chainid(E) =< 1158),(block_coinbase(E) >= 0),(block_coinbase(E) =< 146),(block_prevrandao(E) >= 0),(block_prevrandao(E) =< 1158),(block_gaslimit(E) >= 0),(block_gaslimit(E) =< 1158),(block_number(E) >= 0),(block_number(E) =< 1158),(block_timestamp(E) >= 0),(block_timestamp(E) =< 1158),(msg_sender(E) >= 0),(msg_sender(E) =< 146),(msg_value(E) >= 0),(msg_value(E) =< 1158),(tx_origin(E) >= 0),(tx_origin(E) =< 146),(tx_gasprice(E) >= 0),(tx_gasprice(E) =< 1158),(msg_sig(E) = 35),(select(bytes_tuple_accessor_array(msg_data(E)), 0) = 208),(select(bytes_tuple_accessor_array(msg_data(E)), 1) = 227),(select(bytes_tuple_accessor_array(msg_data(E)), 2) = 13),(select(bytes_tuple_accessor_array(msg_data(E)), 3) = 176),(bytes_tuple_accessor_length(msg_data(E)) >= 4),(K = F),(M = 0),(N = G),block_11_function_deposit__39_80_0(M,B,C,D,E,F,G,K,N,O,P),summary_3_function_deposit__39_80_0(A,B,C,D,E,J,N,H,I).
interface_0_bank_80_0(A,B,C,D,E) :- (F = 0),summary_4_function_deposit__39_80_0(F,A,B,C,G,H,I,D,E),interface_0_bank_80_0(A,B,C,H,I).
block_12_function_withdraw__79_80_0(A,B,C,D,E,F,G,H,I,J,K,L) :- true.
block_13_withdraw_78_80_0(A,B,C,D,E,F,G,H,I,J,K,L) :- (I = F),(A = 0),(J = G),(K = H),block_12_function_withdraw__79_80_0(A,B,C,D,E,F,G,H,I,J,K,L).
nondet_call_15_0(A,B,C,D,E,F,G,H) :- nondet_interface_1_bank_80_0(A,B,C,D,E,F,G,H).
summary_5_function_withdraw__79_80_0(A,B,C,D,E,F,G,H,I,J,K) :- (A >= 1),(L = state_type(store(balances(M), B, (select(balances(M), B) - N)))),(bytes_tuple_accessor_length(O) = 0),(N =< 1158),(N >= 0),(N = K),(P =< 146),(P >= 0),(P = msg_sender(E)),(Q = R),(R = mapping__address_to_uint256___tuple(store(mapping__address_to_uint256___tuple_accessor_array(S), T, U), mapping__address_to_uint256___tuple_accessor_length(S))),(V =< 1158),(V >= 0),(V = select(mapping__address_to_uint256___tuple_accessor_array(S), T)),(S = W),(U =< 1158),(U >= 0),(U = (X - Y)),(X >= 0),(X =< 1158),(X =< 1158),(X >= 0),(X = select(mapping__address_to_uint256___tuple_accessor_array(W), T)),(T =< 146),(T >= 0),(T = msg_sender(E)),(Z = W),(Y =< 1158),(Y >= 0),(Y = K),A1,\+(((A1; (B1, C1)), ((\+(B1); \+(C1)); \+(A1)))),\+(((C1; (D1 >= E1)), (\+((D1 >= E1)); \+(C1)))),(D1 >= 0),(D1 =< 1158),\+((B1, (\+((D1 >= 0)); \+((D1 =< 1158))))),(D1 = select(mapping__address_to_uint256___tuple_accessor_array(W), F1)),\+((B1, (\+((F1 >= 0)); \+((F1 =< 146))))),(F1 = msg_sender(E)),(G1 = W),\+((B1, (\+((E1 >= 0)); \+((E1 =< 1158))))),(E1 = K),\+(((B1; ((H1 - I1) >= 1)), (\+(((H1 - I1) >= 1)); \+(B1)))),(I1 = 0),(H1 =< 1158),(H1 >= 0),(H1 = K),(K >= 0),(K =< 1158),\+(J1),block_13_withdraw_78_80_0(K1,B,C,D,E,F,G,H,M,W,K,J1),nondet_call_15_0(A,B,C,D,L,R,I,J).
block_14_return_function_withdraw__79_80_0(A,B,C,D,E,F,G,H,I,J,K,L) :- M,\+(((M; L), (\+(L); \+(M)))),\+(((L; tuple__bool,bytes___accessor_0(N)), (\+(tuple__bool,bytes___accessor_0(N)); \+(L)))),(A = 0),(O = state_type(store(balances(P), B, (select(balances(P), B) - Q)))),(bytes_tuple_accessor_length(R) = 0),(Q =< 1158),(Q >= 0),(Q = K),(S =< 146),(S >= 0),(S = msg_sender(E)),(T = U),(U = mapping__address_to_uint256___tuple(store(mapping__address_to_uint256___tuple_accessor_array(V), W, X), mapping__address_to_uint256___tuple_accessor_length(V))),(Y =< 1158),(Y >= 0),(Y = select(mapping__address_to_uint256___tuple_accessor_array(V), W)),(V = Z),(X =< 1158),(X >= 0),(X = (A1 - B1)),(A1 >= 0),(A1 =< 1158),(A1 =< 1158),(A1 >= 0),(A1 = select(mapping__address_to_uint256___tuple_accessor_array(Z), W)),(W =< 146),(W >= 0),(W = msg_sender(E)),(C1 = Z),(B1 =< 1158),(B1 >= 0),(B1 = K),D1,\+(((D1; (E1, F1)), ((\+(E1); \+(F1)); \+(D1)))),\+(((F1; (G1 >= H1)), (\+((G1 >= H1)); \+(F1)))),(G1 >= 0),(G1 =< 1158),\+((E1, (\+((G1 >= 0)); \+((G1 =< 1158))))),(G1 = select(mapping__address_to_uint256___tuple_accessor_array(Z), I1)),\+((E1, (\+((I1 >= 0)); \+((I1 =< 146))))),(I1 = msg_sender(E)),(J1 = Z),\+((E1, (\+((H1 >= 0)); \+((H1 =< 1158))))),(H1 = K),\+(((E1; ((K1 - L1) >= 1)), (\+(((K1 - L1) >= 1)); \+(E1)))),(L1 = 0),(K1 =< 1158),(K1 >= 0),(K1 = K),(K >= 0),(K =< 1158),\+(M1),block_13_withdraw_78_80_0(N1,B,C,D,E,F,G,H,P,Z,K,M1),nondet_call_15_0(A,B,C,D,O,U,I,J).
summary_5_function_withdraw__79_80_0(A,B,C,D,E,F,G,H,I,J,K) :- block_14_return_function_withdraw__79_80_0(A,B,C,D,E,F,G,H,I,J,K,L).
block_16_function_withdraw__79_80_0(A,B,C,D,E,F,G,H,I,J,K,L) :- true.
summary_6_function_withdraw__79_80_0(A,B,C,D,E,F,G,H,I,J,K) :- (L = state_type(store(balances(M), B, (select(balances(M), B) + N)))),((select(balances(M), B) + N) >= 0),((select(balances(M), B) + N) =< 1158),(N >= msg_value(E)),((block_prevrandao(E) + 0) >= 1),(block_basefee(E) >= 0),(block_basefee(E) =< 1158),(block_chainid(E) >= 0),(block_chainid(E) =< 1158),(block_coinbase(E) >= 0),(block_coinbase(E) =< 146),(block_prevrandao(E) >= 0),(block_prevrandao(E) =< 1158),(block_gaslimit(E) >= 0),(block_gaslimit(E) =< 1158),(block_number(E) >= 0),(block_number(E) =< 1158),(block_timestamp(E) >= 0),(block_timestamp(E) =< 1158),(msg_sender(E) >= 0),(msg_sender(E) =< 146),(msg_value(E) >= 0),(msg_value(E) =< 1158),(tx_origin(E) >= 0),(tx_origin(E) =< 146),(tx_gasprice(E) >= 0),(tx_gasprice(E) =< 1158),(msg_value(E) = 0),(msg_sig(E) = 77),(select(bytes_tuple_accessor_array(msg_data(E)), 0) = 46),(select(bytes_tuple_accessor_array(msg_data(E)), 1) = 26),(select(bytes_tuple_accessor_array(msg_data(E)), 2) = 125),(select(bytes_tuple_accessor_array(msg_data(E)), 3) = 77),(bytes_tuple_accessor_length(msg_data(E)) >= 4),(M = F),(O = 0),(P = G),(Q = H),block_16_function_withdraw__79_80_0(O,B,C,D,E,F,G,H,M,P,Q,R),summary_5_function_withdraw__79_80_0(A,B,C,D,E,L,P,Q,I,J,K).
interface_0_bank_80_0(A,B,C,D,E) :- (F = 0),summary_6_function_withdraw__79_80_0(F,A,B,C,G,H,I,J,D,E,K),interface_0_bank_80_0(A,B,C,H,I).
contract_initializer_entry_18_bank_80_0(A,B,C,D,E,F,G,H,I) :- (I = H),(G = F),(A = 0).
contract_initializer_after_init_19_bank_80_0(A,B,C,D,E,F,G,H,I) :- contract_initializer_entry_18_bank_80_0(A,B,C,D,E,F,G,H,I).
contract_initializer_17_bank_80_0(A,B,C,D,E,F,G,H,I) :- contract_initializer_after_init_19_bank_80_0(A,B,C,D,E,F,G,H,I).
implicit_constructor_entry_20_bank_80_0(A,B,C,D,E,F,G,H,I) :- (select(balances(G), B) >= msg_value(E)),(G = F),(A = 0),(I = H),(I = mapping__address_to_uint256___tuple(const(0), 0)).
summary_constructor_2_bank_80_0(A,B,C,D,E,F,G,H,I) :- (A >= 1),implicit_constructor_entry_20_bank_80_0(J,B,C,D,E,F,K,H,L),contract_initializer_17_bank_80_0(A,B,C,D,E,K,G,L,I).
summary_constructor_2_bank_80_0(A,B,C,D,E,F,G,H,I) :- (A = 0),implicit_constructor_entry_20_bank_80_0(J,B,C,D,E,F,K,H,L),contract_initializer_17_bank_80_0(A,B,C,D,E,K,G,L,I).
interface_0_bank_80_0(A,B,C,D,E) :- ((block_prevrandao(F) + 0) >= 1),(block_basefee(F) >= 0),(block_basefee(F) =< 1158),(block_chainid(F) >= 0),(block_chainid(F) =< 1158),(block_coinbase(F) >= 0),(block_coinbase(F) =< 146),(block_prevrandao(F) >= 0),(block_prevrandao(F) =< 1158),(block_gaslimit(F) >= 0),(block_gaslimit(F) =< 1158),(block_number(F) >= 0),(block_number(F) =< 1158),(block_timestamp(F) >= 0),(block_timestamp(F) =< 1158),(msg_sender(F) >= 0),(msg_sender(F) =< 146),(msg_value(F) >= 0),(msg_value(F) =< 1158),(tx_origin(F) >= 0),(tx_origin(F) =< 146),(tx_gasprice(F) >= 0),(tx_gasprice(F) =< 1158),(msg_value(F) = 0),(G = 0),summary_constructor_2_bank_80_0(G,A,B,C,F,H,D,I,E).
error_target_4_0 :- (A = 1),summary_4_function_deposit__39_80_0(A,B,C,D,E,F,G,H,I),interface_0_bank_80_0(B,C,D,F,G).
error_target_4_0 :- (A = 1),summary_6_function_withdraw__79_80_0(A,B,C,D,E,F,G,H,I,J,K),interface_0_bank_80_0(B,C,D,F,G).
ff :- error_target_4_0.
